{% set name = "nlohmann_json" %}
{% set version = "3.9.1" %}
{% set sha256 = "4cf0df69731494668bdd6460ed8cb269b68de9c19ad8c27abc24cd72605b2d5b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nlohmann/json/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  # The json library is header only, so we do not need
  # to export the compiler run-time libraries.
  # They are just needed during the build to perform some checks.
  ignore_run_exports:
    - libcxx

requirements:
  build:
    - cmake {{ cmake }}
    - make  # [linux]
    - {{ compiler('c') }}       # [ppc_arch != "p10"]
    - {{ compiler('cxx') }}     # [ppc_arch != "p10"]
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                             # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}                       # [x86_64 and c_compiler_version == "7.2.*"]
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                             # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}                       # [x86_64 and c_compiler_version == "7.2.*"]

test:
  commands:
    - test -d ${PREFIX}/include/nlohmann  # [linux]
    - test -f ${PREFIX}/include/nlohmann/json.hpp  # [linux]
    - test -f ${PREFIX}/include/nlohmann/json_fwd.hpp  # [linux]
    - test -f ${PREFIX}/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake  # [linux]
    - test -f ${PREFIX}/lib/cmake/nlohmann_json/nlohmann_jsonConfigVersion.cmake  # [linux]
    - test -f ${PREFIX}/lib/cmake/nlohmann_json/nlohmann_jsonTargets.cmake  # [linux]

about:
  home: http://github.com/nlohmann/json
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: JSON for Modern C++
  description: JSON for Modern C++ is a C++11 JSON parser.
  doc_url: http://nlohmann.github.io/json/
  dev_url: http://github.com/nlohmann/json

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
